-- 코드를 입력하세요
SELECT YEAR(O.SALES_DATE) YEAR, MONTH(O.SALES_DATE) MONTH, COUNT (DISTINCT O.USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT O.USER_ID) / (
    SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)="2021"
    ), 1) AS PURCHASED_RATIO
FROM ONLINE_SALE O
JOIN USER_INFO U ON U.USER_ID = O.USER_ID
WHERE YEAR(U.JOINED)="2021"
GROUP BY YEAR, MONTH
ORDER BY MONTH